### ISSUE TITLE
Error with the 'FRA' Lang

### ISSUE THREAD

**Issue by lovamalia** [Arthelon/imgclip#7]
![image](https://user-images.githubusercontent.com/19376789/27642900-71a1d034-5c20-11e7-9abf-81bfdfefdb85.png)
When using the CLI, there is an issue with the FRA language. I don't know if it's from tesseract.js or your module.

**Comment by Arthelon** [comment]
@mmmaxou Seems to be an issue with the fra.traineddata file that is downloaded. You may have better luck with the [official tesseract cli](https://github.com/tesseract-ocr/tesseract). It's a bit more complex but I hope you'll find what you need!

**Comment by Arthelon** [comment]
Closing this for now.
